// -----------------------------------------------------------------------------
// snake_game.js
//
// Author: RAJOJU SAI CHARAN
//
// Description:
// Contains the JavaScript logic for a Snake game designed to be embedded
// within a PDF document generated by generate_snake_pdf.py.
// Handles game state, snake movement, food placement, collision detection,
// scoring, keyboard input (WASD), and updating the display by toggling
// the '.hidden' property of PDF Button fields representing grid cells.
// Visuals are monochrome (visible gray vs. hidden white cells) with a
// blinking food pellet and a static background grid drawn by the PDF itself.
// -----------------------------------------------------------------------------

// --- Game Configuration Constants (Values injected by Python) ---
var gridWidth = ###GRID_WIDTH###;
var gridHeight = ###GRID_HEIGHT###;
var GAME_SPEED_MS = ###INITIAL_GAME_SPEED_MS###;
var INITIAL_SNAKE_LENGTH = ###INITIAL_SNAKE_LENGTH###;

// --- Internal Game Variables ---
var gameLoopInterval = null; // Stores the interval timer ID
var snakeBody = []; // Array of {x, y} coords, head is at index 0
var food = {x: 0, y: 0}; // Food position
var direction = {dx: 1, dy: 0}; // Current movement direction {dx, dy}
var nextDirection = {dx: 1, dy: 0}; // Buffered direction from keyboard input
var score = 0;
var gameOver = false;
var gameStarted = false; // Tracks if the game loop is running
var foodIsVisible = true; // Used for blinking effect

// --- Helper Function: Set Pixel State ---
// Toggles the visibility of a grid cell button field.
function setPixel(x, y, state) {
  // Bounds check to prevent errors accessing invalid coordinates
  if (x < 0 || x >= gridWidth || y < 0 || y >= gridHeight) return;
  try {
    var fieldName = "P_" + x + "_" + y; // Construct field name like "P_10_5"
    var f = this.getField(fieldName);    // Get the PDF field object
    if (f) {
      f.hidden = !state; // Set hidden property (true hides, false shows)
    }
  } catch (e) {
    // Log errors silently in console if possible
    // console.println("SetPixel Error@"+x+","+y+": "+e);
  }
}

// --- Food Placement Logic ---
// Finds a random empty spot on the grid for the food, avoiding the snake.
function placeFood() {
  var foodPlaced = false;
  var maxAttempts = gridWidth * gridHeight; // Prevent infinite loop if grid full
  var attempts = 0;
  while (!foodPlaced && attempts < maxAttempts) {
    food.x = Math.floor(Math.random() * gridWidth);
    food.y = Math.floor(Math.random() * gridHeight);
    var collision = false;
    // Check collision with snake body
    for (var i = 0; i < snakeBody.length; i++) {
      if (snakeBody[i].x === food.x && snakeBody[i].y === food.y) {
        collision = true;
        break;
      }
    }
    if (!collision) { foodPlaced = true; }
    attempts++;
  }
  foodIsVisible = true; // Ensure food is visible when newly placed
  // console.println("Food placed at: " + food.x + "," + food.y);
}

// --- Display Update ---
// Clears the grid and redraws the snake and food based on current state.
function updateDisplay() {
  // 1. Clear ENTIRE grid (hide all cell buttons)
  for (var y = 0; y < gridHeight; y++) {
    for (var x = 0; x < gridWidth; x++) {
      setPixel(x, y, false);
    }
  }
  // 2. Draw Snake Body (show buttons for snake segments)
  for (var i = 0; i < snakeBody.length; i++) {
    setPixel(snakeBody[i].x, snakeBody[i].y, true);
  }
  // 3. Draw Food (show button only if foodIsVisible is true for blinking)
  if (foodIsVisible) {
    setPixel(food.x, food.y, true);
  }
}

// --- Snake Movement & Collision Logic ---
function moveSnake() {
  // Ignore if game isn't running
  if (gameOver || !gameStarted) return;

  // Update current direction from buffered input, preventing 180 degree turns
  // If next direction is opposite to current, ignore it.
  var isOpposite = ((direction.dx === -nextDirection.dx && direction.dx !== 0) ||
                    (direction.dy === -nextDirection.dy && direction.dy !== 0));
  if (!isOpposite) {
     direction.dx = nextDirection.dx;
     direction.dy = nextDirection.dy;
  } // else: keep current direction

  // Calculate new head position
  var head = snakeBody[0];
  var newHead = { x: head.x + direction.dx, y: head.y + direction.dy };

  // Check for collision with walls (grid boundaries)
  if (newHead.x < 0 || newHead.x >= gridWidth || newHead.y < 0 || newHead.y >= gridHeight) {
    gameOver = true;
    console.println("Wall Collision!");
    return;
  }

  // Check for collision with self (check against body segments, starting from index 1)
  for (var i = 1; i < snakeBody.length; i++) {
    if (newHead.x === snakeBody[i].x && newHead.y === snakeBody[i].y) {
      gameOver = true;
      console.println("Self Collision!");
      return;
    }
  }

  // No collision - add the new head to the front
  snakeBody.unshift(newHead);

  // Check if the new head position matches the food position
  if (newHead.x === food.x && newHead.y === food.y) {
    // Food eaten!
    score++;
    console.println("Ate food! Score: " + score);
    placeFood(); // Place new food
    // Do not remove the tail segment - this makes the snake grow
    // TODO: Optionally increase speed here based on score/length
  } else {
    // No food eaten, remove the last tail segment to maintain length
    snakeBody.pop();
  }
}

// --- Keystroke Handling ---
// Called by the hidden text field's Keystroke action.
function handleKeystroke(event) {
    // console.println("Keystroke: change=" + event.change); // Debug if needed
    if (!gameStarted || gameOver) return; // Ignore input if game not running

    var key = event.change.toLowerCase(); // Get pressed key (w, a, s, d)

    // Set the *buffered* next direction based on key press.
    // This buffer is checked in moveSnake() to prevent immediate 180 turns.
    if (key === "w") { nextDirection = { dx: 0, dy: 1 }; }  // Up
    else if (key === "s") { nextDirection = { dx: 0, dy: -1 }; } // Down
    else if (key === "a") { nextDirection = { dx: -1, dy: 0 }; } // Left
    else if (key === "d") { nextDirection = { dx: 1, dy: 0 }; }  // Right

    // Try to prevent the viewer from processing the keystroke further (e.g., typing)
    event.rc = false; // Cancel default action
    event.value = ""; // Clear any text that might have been entered
}

// --- Game Over Handling ---
function gameOverHandler() {
  // Stop the game loop interval timer
  if (gameLoopInterval) { app.clearInterval(gameLoopInterval); }
  gameLoopInterval = null;
  gameStarted = false; // Mark game as stopped
  console.println("Game Over Handler. Final Score: " + score);
  // Show final score in an alert box
  app.alert("Game Over! Score: " + score + "\n(Click Start to play again)");
  // Make Start button visible again
  try { this.getField("StartButton").hidden = false; } catch(e){}
}

// --- Main Game Loop ---
// This function is called repeatedly by app.setInterval
function gameLoop() {
  // If game over flag is set by logic, handle it and exit loop iteration
  if (gameOver) {
    gameOverHandler();
    return;
  }

  // Use try-catch for safety within the interval
  try {
    // 1. Move snake (includes collision checks which might set gameOver)
    moveSnake();

    // 2. Check game over state *again* after moving
    if (!gameOver) {
        // 3. Toggle food visibility for blinking effect
        foodIsVisible = !foodIsVisible;
        // 4. Update the display based on new positions
        updateDisplay();
    } else {
        // If move caused game over, handle it immediately
        gameOverHandler();
    }
  } catch(e) {
    // Log errors and stop the game if something unexpected happens
    console.println("Error in game loop: " + e);
    app.alert("Error in game loop: " + e);
    if(gameLoopInterval) app.clearInterval(gameLoopInterval);
    gameOver = true;
    gameStarted = false;
  }
}

// --- Game Start Function ---
// Called by the "Start Game" button click.
function startGame() {
  // Prevent starting if already running
  if (gameStarted) {
    // console.println("Game already started."); // Optional debug
    return;
  }
  console.println("Start Button Clicked - Initializing Game...");

  // Reset game state variables
  snakeBody = [];
  var startX = Math.floor(gridWidth / 2);
  var startY = Math.floor(gridHeight / 2);
  // Create initial snake body (horizontal line)
  for(var i=0; i < INITIAL_SNAKE_LENGTH; i++) {
     snakeBody.push({x: startX - i, y: startY});
  }
  direction = {dx: 1, dy: 0}; // Start moving right
  nextDirection = {dx: 1, dy: 0};
  placeFood(); // Place initial food
  score = 0;
  gameOver = false;
  gameStarted = true; // Set game started flag

  // Hide the Start button
  try{ this.getField("StartButton").hidden = true; }catch(e){}

  // Attempt to set focus to the keystroke field for WASD input
  // This is important but might fail silently in some viewers.
  // Clicking the page after start might still be needed sometimes.
  try {
      this.getField("KeystrokeCatcher").setFocus();
      console.println("Focus set to KeystrokeCatcher");
  } catch(e) {
      console.println("Could not set focus to KeystrokeCatcher: " + e);
  }

  // Perform initial draw of snake and food
  updateDisplay();

  // Clear any existing interval timer before starting a new one
  if (gameLoopInterval) { app.clearInterval(gameLoopInterval); }

  // Start the main game loop interval
  // Using try-catch directly in setInterval string for robustness against errors inside loop
  gameLoopInterval = app.setInterval("try{gameLoop();}catch(e){console.println('Interval Error: '+e); app.clearInterval(gameLoopInterval);}", GAME_SPEED_MS);

  console.println("Game loop started. Interval ID: " + gameLoopInterval);
  // Verify interval was set
  if (!gameLoopInterval) {
    console.println("ERROR: Failed to set interval!");
    app.alert("ERROR: Failed to set interval!");
  }
}

// --- Initial Setup ---
// This code runs once when the PDF JavaScript context is loaded (due to OpenAction)
console.println("PDF JavaScript Loaded for Snake. Waiting for Start button.");
// Game does not start automatically. Initial state is handled by startGame().